#!/bin/bash

password="wxyz"

if test $(id -u) -ne 0; then
    echo "You must run this script as root." 1>&2
    exit 1
fi

create_ctf_user()
{
    # Create user if it does not exist.
    if ! id ctf > /dev/null 2>&1; then
        useradd -m -d /home/ctf -s /bin/bash ctf
    fi
    # Disable password for account (can't login with password).
    passwd -l ctf > /dev/null
    # Prevent password changing.
    passwd -n 9999 ctf > /dev/null
    # Prevent ctf user from writing to home folder.
    chown -R root:ctf /home/ctf
    chmod 750 /home/ctf
}

copy_flag_to_ctf_user()
{
    cp secret /home/ctf/secret
    chown root:ctf /home/ctf/secret
    #chmod 440 /home/ctf/secret
}

# Create ctf user if it does not exist and update password.
create_ctf_user
echo "ctf:$password" | chpasswd
passwd -u ctf > /dev/null

# Flag must be unaccessible to ctf user.
copy_flag_to_ctf_user

# Announce removal of files.
echo
echo "IMPORTANT: Remove all deployed files (flag, setup)."
echo
