#!/usr/bin/python3

from hashlib import sha256

def generate_password_guesses():
    passwords = []
    with open('./passwords') as f:
        passwords = [x.strip() for x in f.readlines()]

    return passwords

def read_hashes():
    hashes = []
    with open('./hashes') as f:
        hashes = [x.strip() for x in f.readlines()]

    return hashes

def break_hashes(hashes):
    password_guesses = generate_password_guesses()

    for p in password_guesses:
        h = sha256(p.encode('utf-8')).hexdigest()

        if h in hashes:
            print("Broken hash {} -> generated by password {}".format(h, p))

def main():
    hashes = read_hashes()
    break_hashes(hashes)

if __name__ == '__main__':
    main()
